title: Ethan Parks
logo: /assets/img/IMG_5486.jpg
description: Applied ML & NLP · MS Data Science · Mountain Athlete
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
navigation:
  - title: Home
    url: /
  - title: Physiological Time Series
    url: /geomTrnsfmr/
  - title: Text Diagnostics (NLP)
    url: /medVec/
  - title: NFL Modeling
    url: /nflModel/
  - title: AI Agents
    url: /agentSys/
